apiVersion: deployments.plural.sh/v1alpha1
kind: ServiceDeployment
metadata:
  name: kiali
  namespace: apps
spec:
  namespace: istio-system
  repositoryRef:
    kind: GitRepository
    name: istio-setup
  git:
    folder: kiali
    ref: main
  clusterRef:
    kind: Cluster
    name: mgmt
    namespace: infra
