apiVersion: deployments.plural.sh/v1alpha1
kind: ServiceDeployment
metadata:
  name: kiali
  namespace: apps
spec:
  namespace: istio-system
  helm:
    url: https://kiali.org/helm-charts
    chart: kiali-server
    version: 'x.x.x'
    values:
      auth:
        strategy: anonymous
      deployment:
        logger:
          log_level: debug
  clusterRef:
    kind: Cluster
    name: mgmt
    namespace: infra
