apiVersion: deployments.plural.sh/v1alpha1
kind: GitRepository
metadata:
  name: istio-setup
spec:
  url: https://github.com/pluralsh/istio-setup.git
---
apiVersion: deployments.plural.sh/v1alpha1
kind: ServiceDeployment
metadata:
  name: istio-sample-app
  namespace: apps
spec:
  namespace: istio-sample-app
  repositoryRef:
    kind: GitRepository
    name: istio-setup
  git:
    folder: sample-app
    ref: main
  clusterRef:
    kind: Cluster
    name: mgmt
    namespace: infra
